[{
	"resource": "/Users/apple/Desktop/mgt-app/app/ayarlar/logout.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'setLoading'.",
	"source": "ts",
	"startLineNumber": 5,
	"startColumn": 3,
	"endLineNumber": 5,
	"endColumn": 13,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/Users/apple/Desktop/mgt-app/app/ayarlar/logout.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'setError'.",
	"source": "ts",
	"startLineNumber": 6,
	"startColumn": 3,
	"endLineNumber": 6,
	"endColumn": 11,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/Users/apple/Desktop/mgt-app/app/ayarlar/logout.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'isNative'.",
	"source": "ts",
	"startLineNumber": 11,
	"startColumn": 9,
	"endLineNumber": 11,
	"endColumn": 17,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/Users/apple/Desktop/mgt-app/app/ayarlar/logout.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'nativeSignIn'.",
	"source": "ts",
	"startLineNumber": 13,
	"startColumn": 13,
	"endLineNumber": 13,
	"endColumn": 25,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/Users/apple/Desktop/mgt-app/app/ayarlar/logout.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'email'.",
	"source": "ts",
	"startLineNumber": 13,
	"startColumn": 26,
	"endLineNumber": 13,
	"endColumn": 31,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/Users/apple/Desktop/mgt-app/app/ayarlar/logout.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'password'.",
	"source": "ts",
	"startLineNumber": 13,
	"startColumn": 33,
	"endLineNumber": 13,
	"endColumn": 41,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/Users/apple/Desktop/mgt-app/app/ayarlar/logout.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'signInWithEmailPasswordREST'.",
	"source": "ts",
	"startLineNumber": 16,
	"startColumn": 13,
	"endLineNumber": 16,
	"endColumn": 40,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/Users/apple/Desktop/mgt-app/app/ayarlar/logout.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'email'.",
	"source": "ts",
	"startLineNumber": 16,
	"startColumn": 41,
	"endLineNumber": 16,
	"endColumn": 46,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/Users/apple/Desktop/mgt-app/app/ayarlar/logout.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'password'.",
	"source": "ts",
	"startLineNumber": 16,
	"startColumn": 48,
	"endLineNumber": 16,
	"endColumn": 56,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/Users/apple/Desktop/mgt-app/app/ayarlar/logout.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'setError'.",
	"source": "ts",
	"startLineNumber": 40,
	"startColumn": 5,
	"endLineNumber": 40,
	"endColumn": 13,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/Users/apple/Desktop/mgt-app/app/ayarlar/logout.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'setLoading'.",
	"source": "ts",
	"startLineNumber": 42,
	"startColumn": 5,
	"endLineNumber": 42,
	"endColumn": 15,
	"modelVersionId": 2,
	"origin": "extHost1"
}]